### PR TITLE
docs: Update docs to reflect renaming to GenSQL.Gen.clj.adapter

### PR DESCRIPTION
**Pull request by KingMob**

### CODE REVIEW

**Comment by sritchie** [comment]
Thank you for this gardening, this is excellent!

**Comment by sritchie** [comment]
@KingMob , if you want to stick with Zane's commit style (I see `docs: ` above) do you want me to modify the repo so that we only allow PR merges via rebase?

**Review by sritchie — COMMENTED** [review]
lgtm

**Comment by KingMob** [comment]
> @KingMob , if you want to stick with Zane's commit style (I see `docs: ` above) do you want me to modify the repo so that we only allow PR merges via rebase?

@sritchie I guess so. I haven't asked Zane why he prefers that, but I personally have no strong opinion between rebases and merges. I do low-key dislike squash merges, though: they hamper bisection, and don't seem worth it until you have triple-digit numbers of contributors.

**Comment by sritchie** [comment]
Interesting, I have been preferring a squash merge, probably because I also prefer a detailed PR title and description (and find that I've never been able to get myself or anyone to add this level of care and granularity to commit messages). But Zane's strong opinion should win in this case!

**Comment by KingMob** [comment]
That’s fair. I’m the sort who will do whatever, and then after PR approval, try to rewrite the history into a nice clean sequence of commits, but I freely admit, this is slightly insane and time-consuming 😛 

Of course, powerful rebasing abilities are part of why I’ve fallen in love with jj. I don’t think I’ll ever use git again.

**Pull request merged**
